[package]
name = "bb8-postgres"
version = "0.1.0"
authors = ["Kyle Huey <khuey@kylehuey.com>"]

[dependencies]
bb8 = { path = ".." }
futures = "0.1"
postgres-shared = "0.4"
tokio-core = "0.1"
tokio-postgres = "0.3"

[dev-dependencies]
futures-state-stream = "0.2"
